### ISSUE TITLE
網站與設計稿比例不符

### ISSUE THREAD

**Issue by Jerry-Hong** [f2etw/fedc2018#11]
設計稿的寬度是 1440 px，現在完全是照 1440 寬度下的 px 去切，比例會不符設計稿。

**Comment by Rplus** [comment]
有設計稿這東西？

**Comment by yutin1987** [comment]
考慮螢幕多尺寸 是否相對位置正確就好？

**Comment by Jerry-Hong** [comment]
@yutin1987 我全部改用 rem 了，這張先關掉

**Comment by Rplus** [comment]
你的 `1rem = 10px` 根本坑人呀
Firefox 跟 Chrome 不一樣大小…

**Comment by Jerry-Hong** [comment]
@Rplus

這是 rem 的原罪 跟 1rem 等於 幾 px 無關

如果要精確一致的話 只能改回 px

**Comment by Jerry-Hong** [comment]
@Rplus Firefox 也太恐怖了 我等一下修正

**Comment by Rplus** [comment]
我是覺得 @Jerry-Hong 你回問題似乎回錯了
比例不對跟是不是用 rem 並無相關
