### ISSUE TITLE
 FB 活動頁 Banner (500 x 262) 

### ISSUE THREAD

**Issue by yutin1987** [f2etw/fedc2018#3]

**Comment by yutin1987** [comment]
活動連結： https://www.facebook.com/events/196401260949269/permalink/196403427615719/?notif_t=feedback_reaction_generic&notif_id=1519888262681126

**Comment by dongisme** [comment]
https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_500x262.jpg

![](https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_500x262.jpg?raw=true)

**Comment by Rplus** [comment]
@dongisme 可以在 commit message 裡用下面這些關鍵字
這麼一來，只要 push 出去就會自動關掉這支 issue 了
https://help.github.com/articles/closing-issues-using-keywords/

例: `close #3`

**Comment by dongisme** [comment]
謝謝 @Rplus  我之後會在 push 的時候試試看
