### ISSUE TITLE
Call for Sponsors & Call for Speakers 按鈕

### ISSUE THREAD

**Issue by cjies** [f2etw/fedc2018#35]
目前這兩顆按鈕還沒有實作 RWD，在手機上應該要放在 `<Main>` 的下面：
<img width="171" alt="screen shot 2018-03-07 at 12 01 20 am" src="https://user-images.githubusercontent.com/5558360/37043051-b03261de-219a-11e8-81c0-c612b4d8476c.png">

一般網頁則向 `<Header>` 對齊，放在 burger 的右側：
<img width="582" alt="screen shot 2018-03-06 at 11 57 51 pm" src="https://user-images.githubusercontent.com/5558360/37043107-cd7688a6-219a-11e8-9444-2c06763bea2d.png">

**Comment by cjies** [comment]
Link changes refer to #25.

**Comment by cjies** [comment]
@dongisme 想確定一下這兩個按鈕只會出現在首頁？在子頁面一樣會有這兩顆按鈕嗎？

**Comment by Rplus** [comment]
我認為要分兩群處理

`header` 上的是每頁都會出現
而 `main` 的是首頁而已
而且這兩顆在不久後應該會撤掉

**Comment by cjies** [comment]
@Rplus Yes.

我打算將這兩個 buttons 從 `<Header>` 上拔出來。
如果確定只有首頁會出現的話，我就會直接放進 `<Main>`內。

**Comment by dongisme** [comment]
目前應該是只會出現在首頁，贊助跟講者確定內容後,就會拿掉
