### ISSUE TITLE
Firefox 中，「Buy Ticket」文字沒有垂直置中

### ISSUE THREAD

**Issue by kevinptt0323** [f2etw/fedc2018#47]
![2018-03-15 22 31 52](https://user-images.githubusercontent.com/5292982/37469678-c950cc3e-28a0-11e8-909e-217c9602c22f.png)

- 測試環境1
  - Mac OS X 10.11.6
  - Firefox 56.0b12
- 測試環境2
  - Fedora 27
  - Firefox 58.0.2

看起來是 `alignment-baseline="middle"` 的問題，改用 `dominant-baseline="middle"` 即可。

Ref: [alignment-baseline - SVG | MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline#Elements)

**Comment by wl00887404** [comment]
感謝你的回報  :+1:

**Comment by Rplus** [comment]
註記哪個 commit 修正這 issue 後再關 issue
不要直接關

**Comment by wl00887404** [comment]
commit 在這個 https://github.com/f2etw/fedc2018/commit/6a1bd6d69fa75bfe29ace005351578752947eed8
@Rplus 謝謝提醒
@kevinptt0323 再次感謝你

**Comment by Jerry-Hong** [comment]
@wl00887404 在 commit 訊息的時候加一下 #47 就會自動連結過來

另外 commit 訊息 `feat(web): fix BuyTicket text position` 的 feat 是指 feature，但這裡是 fix
比較好的 commit message 是 
```
fix(web): BuyTicket text vertical position for Firefox.

Close #47
```

可以參考這張圖
![commit message](https://user-images.githubusercontent.com/5695689/37507208-5770341e-2928-11e8-954a-f1393fba2bc9.jpg)

**Comment by Rplus** [comment]
開 gitter 通知吶！
https://gitter.im/f2etw/fedc2018
