### ISSUE TITLE
前端社團 封面 更新為 FEDC 視覺

### ISSUE THREAD

**Issue by yutin1987** [f2etw/fedc2018#5]

**Comment by dongisme** [comment]
https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_500x262.jpg

![](https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_500x262.jpg?raw=true)

**Comment by Rplus** [comment]
@yutin1987 你要的是[社團](https://www.facebook.com/groups/f2e.tw/)封面還是[社團活動](https://www.facebook.com/events/196401260949269/)封面？
size 不太一樣唷

**Comment by dongisme** [comment]
https://www.facebook.com/groups/f2e.tw/
是指這個封面圖嗎？

**Comment by yutin1987** [comment]
@dongisme  是的!!! 社團上面的封面，不是活動

**Comment by Rplus** [comment]
@dongisme 盡量不要刪留言

**Comment by dongisme** [comment]
尺寸是851x315?
沒錯吧

**Comment by Rplus** [comment]
Facebook group cover size: 1640 x 856 px

**Comment by Rplus** [comment]
不太建議太靠上或下
會切到字

https://louisem.com/wp-content/uploads/2017/12/facebook-group-cover-photo-size-2018.png

**Comment by dongisme** [comment]
![](https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_1640x856.jpg?raw=true)

**Comment by Rplus** [comment]
DONE.
https://www.facebook.com/groups/f2e.tw/permalink/1574771075893585/
