### ISSUE TITLE
Wording suggestions in about page

### ISSUE THREAD

**Issue by cjies** [f2etw/fedc2018#52]
`It is` sounds weird... 😕
Maybe `We are the Taiwan's biggest ...` is better?

![screen shot 2018-05-11 at 11 12 36 am](https://user-images.githubusercontent.com/5558360/39904796-5e290168-550c-11e8-93e4-fbc9a4603501.png)

**Comment by Rplus** [comment]
都省略直接以 `Taiwan… ` 開頭就都沒事了

不過我覺得不就人多了點而已嘛
自稱「台灣最大」感覺毛毛的便是…

另一點是，
個人覺得 About 應該是要介紹這個 FEDC，而不是主辦單位

或是說，你去逛桐花季宣傳網站
點進去看 about 預期會看到客家委員會的介紹嗎？ XDDD

**Comment by wl00887404** [comment]
Sorry 
按錯了
