### ISSUE TITLE
招募 Sponsor 社團貼文視覺

### ISSUE THREAD

**Issue by yutin1987** [f2etw/fedc2018#6]
![fb_02](https://user-images.githubusercontent.com/2505934/36930711-fbb1cd9a-1ee1-11e8-88eb-e894a1f108cb.jpg)
需要將這張圖改成 『Sponsor』

**Comment by dongisme** [comment]
https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_02_sponsors.jpg

![](https://github.com/f2etw/fedc2018/blob/master/design/FbPromo/fb_02_sponsors.jpg?raw=true)
